language: python
python:
- 3.7
script:
- black --check .
- black --check .
- flake8 .
- coverage run -a --source="." manage.py
install:
- pip install -r requirements.txt
- pip install black
- pip install flake8
- pip install coverage
- pip install coveralls
cache:
  Expires: 0
  Pragma: no-cache
after_success:
- coveralls
deploy:
- provider: elasticbeanstalk
  access_key_id: 'AKIAVQZPIVYUF6UDMH6I'
    # secure: 'PlmC0YexbqHAO3i25h741pkj6098dg4IRJwkNg7xPzNdw8RbeHJUI\+ZTYEBBoaFR5l\+OF3pq4gm45h42CL25ERLJSe4zpDK5NymTAVomqiXGbChm3SlPvcKiUqY8C\+CyTyN\+iofLTTdots71sop\+gMx7mSBXpHDJ\/7j2i39VMa84atvzqUGLJZWOl2vl59vtWS\/\/VW2FmRVNaSXbFzjEEI9ff2oaieMCsFAQ7Rs\+oOjNtOffzNqZVzbe1IGE3v0f3wKMS9LOvLHmhGp6z6diEB1KoaxdDU\/Wwz9Ji\/OD68jc1Apt9\+zQKihsuxDbJe0dZAr0JtSavZxYU9P2UXBc94nqG9P0donzQfrq7WeDNkt2F3td4cBf5AhVJfoaXaDJw6JYwdkug61s2uO4Wa4MQq3Ov4wn\/f\/cMUyEoTxPi\+BBmQ4SAuNk2SPqYBN8toGjPjX60g1\/Yx1ZNs\/cPoCTyZaSD6EJVurEGv\+\+r\/xMdFYT\/LiVgvrYHyF7mvDZUGDHiruj\+XHn6KGcqmi1d8E8QF38Fl4TGbt5JEXDdk2r4llJ9kU\/BBLX\/rr\/\+qUuIK4lRZmzW6uru1E\/LZpgr9uNKSFHHc8Gj6zRxRS4y7aCYPJOVOrwEufLX\+SOEuHoxWNiMgjl3Hxly4MP8Lyp\/h6wnn457OV2497k6pGThB6rOBw\='
  secret_access_key: 'ga2u0\!f\%3\(q\!lcn\_\+uw\-\+\(tn\^lqls\*5tjau\#iuwt\%c3a\=y0a\(6'
  #  secure: 'CEVJ19O88cxUDcGkrDDXywSg3zEULgqmHJTKERbPdUgNn9xIoqp
  #  \+U3WZcdt8k4hu8EufJgeIfJfC1eENHMXlshgcfT
  #  \+oci8b2ttnVpPhD2XuK4WA1QIzYdL0uEnqxd\/aqUD0kCmXl2XU\/\/LIscdIvpbELGWbLlLF5WzzVdLsACK6vTYf\+TsTzSfY1dIq2n2895LzR8GSNpLvuOQr\/thRCKsbA9q4JD1KRu5nP3Yw1Iah\/zXOUN9edF3e\/bAHVNCUgUmStxTTLiaqUkZvIJ4\/PdPHkfpu4izeBepzE\+F\/hMjR0QY6hVdhzV76p\/ZrVR\/PJJvev8V4EqF7vv5jcSEqKb\/TZq52kWs6kDN5KNc9qDrUUR1GXwMru5ckv\+eDJu6jqm5Jd6LKzhV15U3mGT1RsjnKlVKopICG\/HzawByjxehoa\/UdJ1uYpQRFOvjhxpSf\+4fBRFPvcZeWF7UiPRdgsP3dcWNGJEL9DdNFLhrTiMakTm95b2urhGoG9PQ2MBELSfJL\+sqxLng0eBcU0yNaNpJWIMlXN5ck4VA3oG0qtOM3esa0\+r0BfKJupSsKpjcYSuvzUvGZtE4euf7eYBmlL6jz8MBpQyJs67mAtLm\/WeSOByBPMM22cr3\/i\+jrI4ViSArinlhXbMD2KfSWCAWA6d7vQZttqBXd91vltTHcmpI\='
  region: "us-east-1"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-east-1-379666869800"
  on:
    branch: main
  skip_cleanup: true
